version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd dockerJava
      - mvn clean install
  post_build:
    commands:
      echo Build completed on `date`
artifacts:
  files:
     dockerJava/target/dockerJava-0.0.1-SNAPSHOT.jar